#Eureka server多实例配置
server:
  port: 8080
spring:
  application:
    name: ad-eureka
eureka:
  instance:
    hostname: server1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server2:8081/eureka/
#    fetch-registry: false
#    register-with-eureka: false
