#Eureka server多实例配置
server:
  port: 8081
spring:
  application:
    name: ad-eureka
eureka:
  instance:
    hostname: server2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8080/eureka/

